apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-api-server-check-deploy-scaler
  namespace: app-development
spec:
  scaleTargetRef:
    kind: Deployment
    name: http-api-server-check-deploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: http-api-server-check-deploy
  name: http-api-server-check-deploy
  namespace: app-development
spec:
  selector:
    matchLabels:
      run: http-api-server-check-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: http-api-server-check-deploy
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - image: edmondandy/http-api-server-check-deploy:sulingzhang-dev-4ACD54C8-52E8-40A9-B7BF-9A2995965CFA
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: ENVIRONMENT
              value: development
            - name: STAGE
              value: development
          name: http-api-server-check-deploy
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/ssl/certs
            name: ca-certificates
      volumes:
        - name: ca-certificates
          hostPath:
            path: /etc/ssl/certs
---
apiVersion: v1
kind: Service
metadata:
  name: http-api-server-check-deploy
  namespace: app-development
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: http-api-server-check-deploy
  type: LoadBalancer
