// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: proto/replicas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRequest) Reset() {
	*x = ReplicaRequest{}
	mi := &file_proto_replicas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRequest) ProtoMessage() {}

func (x *ReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRequest.ProtoReflect.Descriptor instead.
func (*ReplicaRequest) Descriptor() ([]byte, []int) {
	return file_proto_replicas_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplicaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReplicaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Replicas          int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,4,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,5,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	UpdatedReplicas   int32                  `protobuf:"varint,6,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplicaResponse) Reset() {
	*x = ReplicaResponse{}
	mi := &file_proto_replicas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaResponse) ProtoMessage() {}

func (x *ReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaResponse.ProtoReflect.Descriptor instead.
func (*ReplicaResponse) Descriptor() ([]byte, []int) {
	return file_proto_replicas_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplicaResponse) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ReplicaResponse) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *ReplicaResponse) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *ReplicaResponse) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

var File_proto_replicas_proto protoreflect.FileDescriptor

const file_proto_replicas_proto_rawDesc = "" +
	"\n" +
	"\x14proto/replicas.proto\x12\breplicas\"B\n" +
	"\x0eReplicaRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe0\x01\n" +
	"\x0fReplicaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12%\n" +
	"\x0eready_replicas\x18\x04 \x01(\x05R\rreadyReplicas\x12-\n" +
	"\x12available_replicas\x18\x05 \x01(\x05R\x11availableReplicas\x12)\n" +
	"\x10updated_replicas\x18\x06 \x01(\x05R\x0fupdatedReplicas2^\n" +
	"\x0eReplicaService\x12L\n" +
	"\x15GetDeploymentReplicas\x12\x18.replicas.ReplicaRequest\x1a\x19.replicas.ReplicaResponseB\x0fZ\rgo_grpc/protob\x06proto3"

var (
	file_proto_replicas_proto_rawDescOnce sync.Once
	file_proto_replicas_proto_rawDescData []byte
)

func file_proto_replicas_proto_rawDescGZIP() []byte {
	file_proto_replicas_proto_rawDescOnce.Do(func() {
		file_proto_replicas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replicas_proto_rawDesc), len(file_proto_replicas_proto_rawDesc)))
	})
	return file_proto_replicas_proto_rawDescData
}

var file_proto_replicas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_replicas_proto_goTypes = []any{
	(*ReplicaRequest)(nil),  // 0: replicas.ReplicaRequest
	(*ReplicaResponse)(nil), // 1: replicas.ReplicaResponse
}
var file_proto_replicas_proto_depIdxs = []int32{
	0, // 0: replicas.ReplicaService.GetDeploymentReplicas:input_type -> replicas.ReplicaRequest
	1, // 1: replicas.ReplicaService.GetDeploymentReplicas:output_type -> replicas.ReplicaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_replicas_proto_init() }
func file_proto_replicas_proto_init() {
	if File_proto_replicas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replicas_proto_rawDesc), len(file_proto_replicas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replicas_proto_goTypes,
		DependencyIndexes: file_proto_replicas_proto_depIdxs,
		MessageInfos:      file_proto_replicas_proto_msgTypes,
	}.Build()
	File_proto_replicas_proto = out.File
	file_proto_replicas_proto_goTypes = nil
	file_proto_replicas_proto_depIdxs = nil
}
